AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-aws-layer

     SAM Template for a Stripe Layer

Resources:
    StripeLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Stripe for serverlass app
            ContentUri: './dist/'
            CompatibleRuntimes:
                - nodejs20.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Delete

Outputs:
    StripeLayerArn:
        Description: 'AWS Stripe Layer'
        Value: !Ref StripeLayer
